version: "3"

services: 
  db:
    image: mariadb:latest
    container_name: mariadb
    env_file:  
      - .env
    volumes: 
      - ./estudiantes.sql:/docker-entrypoint-initdb.d/estudiantes.sql

  db_admin:
    image: bitnami/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on: 
      - "db"
    env_file:  
      - .env
    ports: 
      - "81:8080"

  app:
    build: .
    container_name: app
    volumes:
      - ./estudiantes/:/var/www/html/
    depends_on: 
      - "db"
    env_file:  
      - .env
    ports: 
      - "80:8080"